### ISSUE TITLE
Is this compatible with this toy?

### ISSUE THREAD

**Issue by Andrea-58** [Sesch69/LovenseBSControl#1]
Is this compatible with this product? Link: https://www.amazon.com/dp/B094JD78BD

**Comment by Sesch69** [comment]
Hi Andrea-58,
unfortunately only with toys from the lovense company, the connections are only possible to the Lovense Connect App (www.lovense.com or as amazon example https://www.amazon.com/-/de/dp/B089Q6JVX8 which are using the Lovense Connect App)
best regards,
Sesch69
