### ISSUE TITLE
Can this product be used

### ISSUE THREAD

**Issue by SmartArduino** [Sesch69/LovenseBSControl#2]
Can this product be used
https://www.amazon.com/dp/B094JD78BD

**Comment by SmartArduino** [comment]
After my test, it can be used. The communication protocol is the same

**Comment by Sesch69** [comment]
Ah, so you connected this toy with Lovense Connect? Or another program?

**Comment by SmartArduino** [comment]
another program



Skype: yichone
Wechat: itchenve
WhatsApp: 008618676662425
mail: ***@***.***, ***@***.*** 
document: https://www.gitnova.com/ 
Smart Product site: www.sposmart.com
DIY maker site:www.doit.am

 
From: Sesch69
Date: 2021-06-04 23:36
To: Sesch69/LovenseBSControl
CC: yichone; Author
Subject: Re: [Sesch69/LovenseBSControl] Can this product be used (#2)
Ah, so you connected this toy with Lovense Connect? Or another program?

**Comment by Sesch69** [comment]
Ok, thanks for the hint, I didn't know that this is a common communication protocol for the toys is.

**Comment by Sesch69** [comment]
All toys wich are pssible to control with same API should be possible to use. (Connect with LovenseConnect or similar programs)
