### ISSUE TITLE
Dont Work

### ISSUE THREAD

**Issue by Tushky-Wolf** [Sesch69/LovenseBSControl#3]
Hello,

the Menu dont show up 
it try 

C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Plugins\LovenseBSControl-master\LovenseBSControl-master\LovenseBSControl

-and-

C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Plugins\LovenseBSControl-master\LovenseBSControl

-and-

C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Plugins\LovenseBSControl

-and- 

C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Plugins\

![grafik](https://user-images.githubusercontent.com/84333113/148700608-a03acd52-6a25-4896-8a55-9045bfc064ef.png)

**Comment by Tushky-Wolf** [comment]
may need the .dll

**Comment by Sesch69** [comment]
The .dll is part of the zip file added to the release version. The .dll must be placed into the Plugins folder.

**Comment by MatsSchrader** [comment]
I don't see a .dll file in the zip or anywhere in this repository

**Comment by Sesch69** [comment]
DLL in a ZIP file to download is in the GIT Release View available under each release entry
