### ISSUE TITLE
please update to bs 1.21

### ISSUE THREAD

**Issue by vdsap** [Sesch69/LovenseBSControl#4]
Loading settings error in mod settings menu, can't click on anything

**Comment by AnonModder** [comment]
just in case you're still looking

https://github.com/Sesch69/LovenseBSControl/pull/5#issuecomment-1226087110

**Comment by Sesch69** [comment]
Issue should be fixed with 1.2.8

**Comment by Sesch69** [comment]
Small problems with saving the config, but this is on BSML lib issue. Basic configuration and settings are possible again
